### Variables
@port = 3000

// use the event id variable by changing ___ to the id of the event created or that you would like to access
@testeventid = 663918cfdcac880136f8d798



#- Endpoints

### Get menu
GET http://localhost:{{port}}/api/menu

### Get events
GET http://localhost:{{port}}/api/events

### Get events by ID
GET http://localhost:{{port}}/api/events/{{testeventid}}

### Post events
POST http://localhost:{{port}}/api/events
Content-Type: application/json

    {
        "name": "Test Item",
        "date": "1, 1, 2025",
        "hours": "Hours Here",
        "location": "Appleton" 
    }

### Put events
PUT http://localhost:{{port}}/api/events/{{testeventid}}
Content-Type: application/json

    {
        "name": "Test Item Updated",
        "date": "1, 1, 2026",
        "hours": "Updated Hours",
        "location": "Menasha" 
    }

### Delete events
DELETE http://localhost:{{port}}/api/events/{{testeventid}}

### Add new menu item

POST http://localhost:{{port}}/api/menu
Content-Type: application/json

{
  "item": "Test item",
  "description": "description here",
  "price": "$3.99"
}

### Update menu item
PUT http://localhost:{{port}}/api/menu/{{testeventid}}
Content-Type: application/json

{
    "item": "Test item updated",
    "description": "description here",
    "price": "$4.99"
}

### Delete menu items
DELETE http://localhost:{{port}}/api/menu/{{testeventid}}