### Variables
@port = 3000


### Get menu items

GET http://localhost:{{port}}/api/menu

### Add new menu item

POST http://localhost:{{port}}/api/menu
Content-Type: application/json

{
  "item": "Test item",
  "description": "description here",
  "price": "$3.99"
}